version: 0.2
phases:
  install:
    commands:
      - echo Starting to install, build modules on `date`
      - export HOME_DIR=$CODEBUILD_SRC_DIR
      - npm set progress=false
      - sh $HOME_DIR/scripts/node-lambdas.sh build
      - aws cloudformation package --template-file $HOME_DIR/scripts/cloudformation/Template.yaml  --s3-bucket charactercreator
        --output-template-file outputTemplate.yaml
  build:
    commands:
      - echo Packaging started on `date`
      - sh $HOME_DIR/scripts/node-lambdas.sh package
  post_build:
    commands:
      - echo Build completed on `date`
      - cd $HOME_DIR/scripts/cloudformation/

cache:
  paths:
    - '/root/.npm/**/*'
    - '/usr/lib/node_modules/**/*'
artifacts:
  types: zip
  files:
    - outputTemplate.yaml
    - scripts/cloudformation/aws-serverless-parameter.json
