AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for deploying all lambdas
Resources:
  authFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ../../lambdas/authFunction/authFunction.zip
      Events:
        GetFuncApi:
          Type: Api
          Properties:
            Path: /authFunction
            Method: POST, GET
  timeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ../../lambdas/timeFunction/timeFunction.zip
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
